---
services:
  sofareinigung-zuerich:
    image: timond3v/sofareinigung-zuerich:1.3.0
    container_name: sofareinigung-zuerich
    pull_policy: if_not_present
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cert:/sofareinigung-zuerich/cert:ro
    ports:
      - 3007:8080
      - 5008:8081