INSERT INTO `zaki`.`comments` (`email`, `name`, `family_name`, `review`, `image`, `date`, `rating`) VALUES
('Hans.Muster@gmail.com', 'Hans', 'Muster', 'Ich bin sehr zufrieden mit der Reinigung meines Sofas. Es sieht wieder aus wie neu.', 'https://picsum.photos/201', '2024-01-08', 4),
('Julia.Müller@gmail.com', 'Julia', 'Müller', 'Hervorragender Service, alles blitzblank!', 'https://picsum.photos/202', '2024-03-09', 5),
('Maximilian.Schuster@gmail.com', 'Maximilian', 'Schuster', 'Der Service war in Ordnung, könnte aber schneller sein.', 'https://picsum.photos/203', '2023-11-06', 3),
('Lena.Meier@gmail.com', 'Lena', 'Meier', 'Super Reinigung! Kann ich nur weiterempfehlen.', 'https://picsum.photos/204', '2024-07-20', 5),
('Felix.Bauer@gmail.com', 'Felix', 'Bauer', 'Leider war die Reinigung nicht gründlich genug.', 'https://picsum.photos/205', '2024-05-15', 2),
('Sophia.Becker@gmail.com', 'Sophia', 'Becker', 'Zufrieden mit dem Ergebnis, allerdings recht teuer.', 'https://picsum.photos/206', '2024-04-22', 4),
('Tobias.Vogel@gmail.com', 'Tobias', 'Vogel', 'Schlechtester Service, den ich je erlebt habe.', 'https://picsum.photos/207', '2023-12-12', 1),
('Laura.Weber@gmail.com', 'Laura', 'Weber', 'Tadellose Arbeit, mein Teppich sieht aus wie neu!', 'https://picsum.photos/208', '2024-02-05', 5),
('Daniel.Richter@gmail.com', 'Daniel', 'Richter', 'Gute Reinigung, schneller Service.', 'https://picsum.photos/209', '2024-08-18', 4),
('Sandra.Fischer@gmail.com', 'Sandra', 'Fischer', 'Es war okay, nicht schlecht, aber auch nicht großartig.', 'https://picsum.photos/200', '2023-09-25', 3),
('Elias.Braun@gmail.com', 'Elias', 'Braun', 'Preis-Leistung stimmt hier absolut nicht.', 'https://picsum.photos/309', '2024-06-18', 1),
('Emma.Keller@gmail.com', 'Emma', 'Keller', 'Ganz okay, aber da geht noch was.', 'https://picsum.photos/265', '2024-09-21', 0),
('David.Brandt@gmail.com', 'David', 'Brandt', 'Der Service war in Ordnung, aber es gibt Luft nach oben.', 'https://picsum.photos/238', '2024-01-01', 3),
('David.Brandt@gmail.com', 'David', 'Brandt', 'Mein Sofa sieht endlich wieder sauber aus.', 'https://picsum.photos/277', '2024-02-14', 3),
('Michael.Schmidt@gmail.com', 'Michael', 'Schmidt', 'Wirklich tolle Arbeit, gerne wieder!', 'https://picsum.photos/229', '2024-05-05', 5),
('David.Brandt@gmail.com', 'David', 'Brandt', 'Schneller Service, aber das Ergebnis hätte besser sein können.', 'https://picsum.photos/216', '2024-10-10', 2),
('Emma.Keller@gmail.com', 'Emma', 'Keller', 'Mein Sofa sieht endlich wieder sauber aus.', 'https://picsum.photos/298', '2024-08-07', 3),
('Clara.Schulz@gmail.com', 'Clara', 'Schulz', 'War alles gut, aber etwas teuer.', 'https://picsum.photos/229', '2024-09-21', 4),
('Emma.Keller@gmail.com', 'Emma', 'Keller', 'Fantastischer Service, ich bin begeistert!', 'https://picsum.photos/265', '2024-05-05', 5),
('Mia.Hoffmann@gmail.com', 'Mia', 'Hoffmann', 'Der Service war in Ordnung, aber es gibt Luft nach oben.', 'https://picsum.photos/238', '2024-02-14', 1),
('Marie.Wagner@gmail.com', 'Marie', 'Wagner', 'Leider bin ich nicht zufrieden, die Flecken sind immer noch da.', 'https://picsum.photos/223', '2024-09-21', 2),
('Lucas.Köhler@gmail.com', 'Lucas', 'Köhler', 'Fantastischer Service, ich bin begeistert!', 'https://picsum.photos/230', '2024-04-20', 2),
('Elias.Braun@gmail.com', 'Elias', 'Braun', 'Ganz okay, aber da geht noch was.', 'https://picsum.photos/254', '2024-07-29', 5),
('Emma.Keller@gmail.com', 'Emma', 'Keller', 'Sehr gründliche Reinigung, top Arbeit.', 'https://picsum.photos/280', '2024-08-07', 4),
('Lucas.Köhler@gmail.com', 'Lucas', 'Köhler', 'Fantastischer Service, ich bin begeistert!', 'https://picsum.photos/212', '2024-04-20', 4),
('David.Brandt@gmail.com', 'David', 'Brandt', 'Mein Sofa sieht endlich wieder sauber aus.', 'https://picsum.photos/272', '2024-04-20', 3),
('Marie.Wagner@gmail.com', 'Marie', 'Wagner', 'Mein Sofa sieht endlich wieder sauber aus.', 'https://picsum.photos/302', '2024-03-12', 1),
('Mia.Hoffmann@gmail.com', 'Mia', 'Hoffmann', 'Mein Sofa sieht endlich wieder sauber aus.', 'https://picsum.photos/222', '2024-04-20', 4),
('Clara.Schulz@gmail.com', 'Clara', 'Schulz', 'Leider bin ich nicht zufrieden, die Flecken sind immer noch da.', 'https://picsum.photos/223', '2024-02-14', 0),
('Marie.Wagner@gmail.com', 'Marie', 'Wagner', 'Schneller Service, aber das Ergebnis hätte besser sein können.', 'https://picsum.photos/235', '2024-06-18', 0);
